Repository brave/leo, pull requests merged in 2024-01, with the labels that each got.

#520 [Icons]: Update icons from Figma
  icons/bookmark-added.svg
  icons/broom.svg
  icons/browser-bookmark-add.svg
  icons/browser-bookmark-checked.svg
  icons/browser-bookmark-normal.svg
  icons/browser-bookmark-plural.svg
  icons/checkbox-indetermined-duotone.svg
  icons/checkbox-indetermined.svg
  icons/meta.d.ts
  icons/meta.js
Labels: puLL-Merge

#526 **BREAKING** [Label]: adds two icon slots to Label to enforce proper spacing
  src/components/label/label.stories.svelte
  src/components/label/label.svelte
Labels: unverified-commits

#496 [Tokens]: Update Elevations, Font Weights & Colors
  src/tokens/browser.tokens.json
  src/tokens/transformation/common/leoParser.js
  src/tokens/transformation/common/tokenFilters.js
  src/tokens/transformation/tailwind/formatCssVars.js
  src/tokens/transformation/tailwind/formatTokens.js
  src/tokens/transformation/tailwind/twShadows.js
  src/tokens/transformation/web/createPropertyFormatter.js
  src/tokens/transformation/web/formatCss.js
  src/tokens/transformation/web/webColorRef.js
  src/tokens/transformation/web/webShadows.js
  src/tokens/universal.tokens.json
  src/tokens/universal.variables.json
  src/tokens/utils.js
Labels: puLL-Merge, unverified-commits

#537 Tokens
  src/tokens/universal.variables.json
Labels: unverified-commits
